#!/usr/bin/env python3
""" test essential functions of the package """
import os
import re
import subprocess
from typing import Final

import pytest

import baselog
from baselog import BaseLog

# REGEX_TS is a regex segment (string) which matches timestamps used in this library
#   e.g. timestamps like: 2023-04-11T11:16:43+0200
REGEX_TS: Final[str] = r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[+-]\d{4}"


# this should probably be a fixture
def read_file_text(path: str, encoding="utf-8", errors=None) -> str:
    """reads the contents of the given file and returns them as a string"""
    with open(path, "rt", encoding=encoding, errors=errors) as textfile:
        return textfile.read()


def unindent(content: str, spaces: int = 4) -> str:
    """given a string, unindent each of its lines by n spaces"""
    regex = r"^\s{n}".replace("n", str(spaces))
    return "\n".join([re.sub(regex, "", line) for line in content.strip().splitlines()])


def test_basics(tmp_log_dir, capsys):
    """test basic operation of baselog"""
    logger = BaseLog(
        "testapp",
        log_dir=tmp_log_dir,
        console_log_level="DEBUG",
        file_log_level="DEBUG",
    )
    assert os.path.exists(logger.log_file)

    logger.debug("I'm a log message at debug level!")
    logger.info("I'm a log message at info level!")
    logger.warning("I'm a log message at warning level!")
    logger.error("I'm a log message at error level!")
    logger.critical("I'm a log message at critical level!")
    captured = capsys.readouterr()

    expected_contents = ""
    for level in ("debug", "info", "warning", "error", "critical"):
        expected_contents += (
            f"{REGEX_TS} - testapp - {level.upper()} - "
            f"I'm a log message at {level} level!\n"
        )

    assert re.match(f"^{expected_contents}$", captured.err) is not None
    assert (
        re.match(f"^{expected_contents}$", read_file_text(logger.log_file)) is not None
    )


def test_uncaught_exception(tmp_run_files, tmp_log_dir):
    """
    ensure that an uncaught exception results in log messages both to stderr and the
    logfile
    """
    prog_file, stderr_log_file = tmp_run_files

    # pytest will get in the way here, so we have to write a small program to a
    # temp_file, run it and check the outputs

    # fmt:off
    prog_file.write_text(unindent("""
    #!/usr/bin/env python3

    import sys
    from baselog import BaseLog

    class RobinExclamation(Exception):
        pass

    def main():
        logger = BaseLog(
            "testapp",
            log_dir=sys.argv[1],
            console_log_level="DEBUG",
            file_log_level="DEBUG",
        )
        raise RobinExclamation("Holy uncaught exceptions, Batman!")

    if __name__ == '__main__':
        main()
    """))
    # fmt:on

    with open(stderr_log_file, "wt", encoding="utf-8") as stderrfh:
        with pytest.raises(subprocess.CalledProcessError):
            subprocess.check_output(
                ("python3", prog_file, tmp_log_dir),
                stderr=stderrfh,
                env={"PYTHONPATH": os.path.dirname(baselog.__file__)},
            )

    # this is the path to the text log file generated by the test app
    # we told the app which directory to log in but the filename is based on
    # a timestamp (by default)
    prog_log_file = [
        os.path.join(tmp_log_dir, filename)
        for filename in os.listdir(tmp_log_dir)
        if filename.startswith("testapp_")
    ][0]
    assert prog_log_file != ""
    prog_log = read_file_text(prog_log_file)

    stderr_log = read_file_text(stderr_log_file)
    assert stderr_log != ""

    for expectation in (
        "testapp - CRITICAL - uncaught RobinExclamation exception:",
        "testapp - CRITICAL - exception L0: Holy uncaught exceptions, Batman!",
        "testapp - CRITICAL - traceback L0: Traceback (most recent call last):",
        "testapp - CRITICAL - traceback L5: RobinExclamation: Holy uncaught exceptions, Batman!",
    ):
        assert expectation in stderr_log
        assert expectation in prog_log


def test_zeropad_fmt():
    """test zeropad_fmt with various inputs"""
    for given_input, expected_output in {
        -224234234: "%010d",
        -42345234: "%09d",
        -6345634: "%08d",
        -745677: "%07d",
        -85673: "%06d",
        -9435: "%05d",
        -723: "%04d",
        -25: "%03d",
        -8: "%02d",
        -1: "%02d",
        0: "%01d",
        1: "%01d",
        6: "%01d",
        14: "%02d",
        375: "%03d",
        9867: "%04d",
        12754: "%05d",
        842845: "%06d",
        4568456: "%07d",
        34262346: "%08d",
        345734577: "%09d",
        9765956799: "%010d",
    }.items():
        assert BaseLog.zeropad_fmt(given_input) == expected_output
